### ISSUE TITLE
Please add sch

### ISSUE THREAD

**Issue by mrx23dot** [markniu/Laser-Filament-Motion-Sensor#1]

**Comment by markniu** [comment]
have added the schematic.

**Comment by mrx23dot** [comment]
Thank you!
Would you also have the firmware?

I guess it needs to know the number of microsteps.
I would also add a sponge in the filament guide since it's an optical sensor.
Is it sensitive to the color of the filament? (eg black vs white)

**Comment by markniu** [comment]
There is a Fsensor_Tool that can set the sensitivity,output signal logic,alarm time, it not necessary for most of user to change the firmware which may confuse and take more hard work for users.

**Comment by markniu** [comment]
I tested several colors of filaments, and this sensor is very sensitive to all of these colors, including black, red, white, and transparent filaments.

**Comment by mrx23dot** [comment]
Ah okay it's not open source then.
Thanks anyway! Great project!
